---
title: "Homework 1"
author: "Sara Burpeau"
date: "February 3, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
```

## Task 1

```{r mh_distance_function}
mh_distance <- function(x, y){
  if(typeof(x) != typeof(y)){
    warning("x and y different vector types")
    return(-1)
  }
  if(is.na(x) == TRUE || is.na(y) == TRUE || 
     is.nan(x) == TRUE || is.nan(y) == TRUE){
    warning("x or y is NA or NaN")
    return(-1)
  }
  if(is.infinite(x) == TRUE || is.infinite(y) == TRUE){
    warning("x or y is an infinite value")
    return(-1)
  }
  if(nchar(x) != nchar(y) & 
     typeof(x) != "logical"){
    warning("x and y different character lengths")
    return(-1)
  }
  if(is.numeric(x) == TRUE & is.numeric(y) == TRUE){
    if(x %% 1 != 0 || y %% 1 != 0)
    warning("x or y contains a decimal")
    return(-1)
  }
   if (typeof(x) == "character"){
     x_list = strsplit(x, "")
     y_list = strsplit(y, "")
     x_vector = unlist(x_list)
     y_vector = unlist(y_list)
    number = x_vector != y_vector
    return(sum(number, na.rm = TRUE))
    }
  if (typeof(x) == "double"){
    xchar = as.character(x)
    ychar = as.character(y)
    x_list = strsplit(xchar, "")
    y_list = strsplit(ychar, "")
    x_vector = unlist(x_list)
    y_vector = unlist(y_list)
    number = x_vector != y_vector
    return(sum(number, na.rm = TRUE))
    }
  if (typeof(x) == "logical"){
    if ((x & y == TRUE) || (x & y == FALSE)){
      return (0)
      }
    return(1)
    }
}

```

## Task 2

**Initial test cases** (return a non-negative modified Hamming distance)

```{r}
mh_distance(x = "abc", y = "abc")
mh_distance(x = T, y = FALSE)
mh_distance(x = "523890", y = "752839")
mh_distance(x = 2341, y = 2350)
```

Added test cases that return a non-negative modified Hamming distance result.

```{r}
# additional test cases go here
```

**Initial test cases** (return values of `-1`)

```{r eval=FALSE}
mh_distance(x = 52, y = 113)
mh_distance(x = "swimming", y = "winning")
mh_distance(x = NA, y = TRUE)
mh_distance(x = 1.5, y = 2.5)
```

Added test cases that return a value of `-1`.

```{r}
# additional test cases go here
```


## Task 3

Consider the pair of vectors `s` and `w` given below.

```{r}
s <- c(26, 50123, 456.12, 8, 0)
w <- c(22, 50000, 451.00, 88, 0)
```

```{r vectorized-mh-distance}
mh_distance_vectorize <- function(s, w){
  for(i in 1:length(s)){
    if(length(s) == length(w)){
      paste0("The modified Hamming distance between ", s[i], " and ", w[i],
             " is ", mh_distance(s[i], w[i]))
    }
  }
}
```


## Task 4

Brief write-up goes here...
